import "./style.css"
import { Inter } from "next/font/google"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h1>Nebuchadnezzar Notes</h1>
        {children}
      </body>
    </html>
  )
}
